development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://192.241.227.182/fayeserver:9292/faye"
  secret_token: "873fbdefb0ee9988e2f70be9bbbe82bd004bcd535911854a00a53f4513523d25"
  signature_expiration: 3600 # one hour
